DROP DATABASE IF EXISTS roster_db;
CREATE DATABASE roster_db;
USE roster_db;

CREATE TABLE department (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE role (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL(8,2) NOT NULL,
  dept_id INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE employee (
  id INT NOT NULL AUTO_INCREMENT,
  fName VARCHAR(30) NOT NULL,
  lName VARCHAR(30) NOT NULL,
  role_id INT NOT NULL,
  mgr_id INT NULL,
  PRIMARY KEY (id)
);